//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarlaEntities1 : DbContext
    {
        public MarlaEntities1()
            : base("name=MarlaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adisyon> Adisyons { get; set; }
        public virtual DbSet<AdisyonOdemeDetay> AdisyonOdemeDetays { get; set; }
        public virtual DbSet<AdisyonSiparisDetay> AdisyonSiparisDetays { get; set; }
        public virtual DbSet<Calisan> Calisans { get; set; }
        public virtual DbSet<CalisanDetay> CalisanDetays { get; set; }
        public virtual DbSet<Depo> Depoes { get; set; }
        public virtual DbSet<DepoMalzemeDetay> DepoMalzemeDetays { get; set; }
        public virtual DbSet<Malzeme> Malzemes { get; set; }
        public virtual DbSet<MalzemeKategori> MalzemeKategoris { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuKategori> MenuKategoris { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
        public virtual DbSet<OdemeYontemi> OdemeYontemis { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<RestaurantMalzemeDetay> RestaurantMalzemeDetays { get; set; }
        public virtual DbSet<Sipari> Siparis { get; set; }
        public virtual DbSet<Tedarikci> Tedarikcis { get; set; }
        public virtual DbSet<Urun> Uruns { get; set; }
        public virtual DbSet<UrunMalzemeDetay> UrunMalzemeDetays { get; set; }
        public virtual DbSet<UrunSiparisDetay> UrunSiparisDetays { get; set; }
    }
}
